sonar.projectKey=transit-bus-js
sonar.projectName=Public Transport Finder

sonar.sources=src

sonar.exclusions=data/**, node_modules/**, dist/**

# Ngôn ngữ lập trình
sonar.language=js
sonar.sourceEncoding=UTF-8